### ISSUE TITLE
Add Link to Badges on Pricing Page with discount details

### ISSUE THREAD

**Issue by samyount** [aptible/aptible-pages#25]
Copy: "Advertise your HIPAA compliance.  Add a [Powered by Aptible Badge](https://www.aptible.com/company/resources/) on your site footer and get a **$100/month discount**.  Open a [support ticket](https://support.aptible.com/contact/) to let us know you are participating."

Make the link go directly to the Badges section of the [Company:Resources Page](https://www.aptible.com/company/resources/).

**Comment by fancyremarker** [comment]
I can grab this. Where on the Pricing Page should this appear?

**Comment by samyount** [comment]
I was thinking just above the unit pricing.

**Comment by gib** [comment]
@samyount - I went ahead and updated www.aptible.com, so this is live too. Let me know if there are any correction / follow up tasks.
